# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-12 16:46
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Ob_opening',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=160)),
                ('starttime', models.DateTimeField()),
                ('endtime', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='Register',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('openid', models.CharField(max_length=100)),
                ('signed', models.IntegerField(default=0)),
                ('opening', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='wxmanager.Ob_opening')),
            ],
        ),
    ]
