# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-12 17:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wxmanager', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='register',
            old_name='opening',
            new_name='ob_opening',
        ),
        migrations.AddField(
            model_name='ob_opening',
            name='max_num',
            field=models.IntegerField(default=100),
        ),
    ]
