# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-16 18:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wxmanager', '0002_auto_20160912_1712'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ob_opening',
            name='max_num',
            field=models.PositiveIntegerField(default=100),
        ),
    ]
