# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-17 17:09
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('wxmanager', '0003_auto_20160916_1831'),
    ]

    operations = [
        migrations.AddField(
            model_name='ob_opening',
            name='endcheckin',
            field=models.DateTimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='ob_opening',
            name='startcheckin',
            field=models.DateTimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
