# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-12 04:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Member',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('openid', models.CharField(max_length=50)),
                ('name', models.CharField(max_length=30)),
                ('wd', models.CharField(choices=[('co', 'departmentCouncil'), ('ma', 'departmentManagement'), ('fa', 'departmentForeignaffair'), ('ia', 'departmentInternalaffair'), ('pr', 'departmentPropogenda'), ('ac', 'departmentAcademic')], default='ac', max_length=2)),
                ('wp', models.CharField(choices=[('mc', 'positionMemberofcouncil'), ('le', 'positionLeader'), ('vl', 'positionViceleader'), ('hd', 'positionHeadofdepartment'), ('vh', 'positionVicehead'), ('md', 'positionMemberofdepartment')], default='md', max_length=2)),
            ],
        ),
    ]
