# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-12 06:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='member',
            name='id',
        ),
        migrations.AddField(
            model_name='member',
            name='gender',
            field=models.CharField(choices=[('f', 'genderFemale'), ('m', 'genderMale')], default='f', max_length=1),
        ),
        migrations.AlterField(
            model_name='member',
            name='openid',
            field=models.CharField(max_length=50, primary_key=True, serialize=False),
        ),
    ]
